import { Metadata } from "next";
import { useEffect } from "react";

export const metadata: Metadata = {
  title: "Abcd",
  description: "Generated by create next app",
};

const Abcd = () => {
  return <div>123</div>;
};

export default Abcd;
